drop extension if exists "pg_net";

create type "public"."climb_type" as enum ('Bouldering', 'Lead', 'Top Rope');


  create table "public"."contact_submissions" (
    "id" bigint generated always as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text not null,
    "email" text not null,
    "role" text,
    "message" text not null,
    "read" boolean not null default false
      );


alter table "public"."contact_submissions" enable row level security;


  create table "public"."gym_admins" (
    "id" uuid not null default gen_random_uuid(),
    "gym_id" bigint,
    "user_id" uuid,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."gym_admins" enable row level security;


  create table "public"."gyms" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "city" text,
    "slug" text,
    "logo_url" text,
    "province" text,
    "tags" public.climb_type[] not null default '{}'::public.climb_type[]
      );


alter table "public"."gyms" enable row level security;


  create table "public"."routes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "wall_id" bigint,
    "gym_id" bigint,
    "name" text,
    "grade" text,
    "color" text,
    "type" text
      );


alter table "public"."routes" enable row level security;


  create table "public"."user_favorite_gyms" (
    "user_id" uuid not null,
    "gym_id" integer not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."user_favorite_gyms" enable row level security;


  create table "public"."user_profiles" (
    "id" uuid not null,
    "email" text,
    "full_name" text,
    "avatar_url" text,
    "created_at" timestamp with time zone default now(),
    "username" text,
    "height" text,
    "home_gym" text,
    "is_superuser" boolean not null default false
      );


alter table "public"."user_profiles" enable row level security;


  create table "public"."videos" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "route_id" bigint,
    "uploaded_by" text,
    "storage_path" text,
    "thumbnail_url" text,
    "views" smallint,
    "mux_asset_id" text,
    "mux_playback_id" text,
    "upload_status" text default 'pending'::text,
    "duration_seconds" integer,
    "aspect_ratio" text,
    "mux_upload_id" text,
    "user_id" uuid
      );


alter table "public"."videos" enable row level security;


  create table "public"."walls" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "gym_id" bigint,
    "name" text,
    "description" text
      );


alter table "public"."walls" enable row level security;

CREATE UNIQUE INDEX climbs_pkey ON public.routes USING btree (id);

CREATE UNIQUE INDEX contact_submissions_pkey ON public.contact_submissions USING btree (id);

CREATE UNIQUE INDEX gym_admins_gym_id_user_id_key ON public.gym_admins USING btree (gym_id, user_id);

CREATE UNIQUE INDEX gym_admins_pkey ON public.gym_admins USING btree (id);

CREATE UNIQUE INDEX gyms_pkey ON public.gyms USING btree (id);

CREATE UNIQUE INDEX user_favorite_gyms_pkey ON public.user_favorite_gyms USING btree (user_id, gym_id);

CREATE UNIQUE INDEX user_favorite_gyms_user_id_gym_id_key ON public.user_favorite_gyms USING btree (user_id, gym_id);

CREATE UNIQUE INDEX user_profiles_pkey ON public.user_profiles USING btree (id);

CREATE UNIQUE INDEX videos_pkey ON public.videos USING btree (id);

CREATE UNIQUE INDEX walls_pkey ON public.walls USING btree (id);

alter table "public"."contact_submissions" add constraint "contact_submissions_pkey" PRIMARY KEY using index "contact_submissions_pkey";

alter table "public"."gym_admins" add constraint "gym_admins_pkey" PRIMARY KEY using index "gym_admins_pkey";

alter table "public"."gyms" add constraint "gyms_pkey" PRIMARY KEY using index "gyms_pkey";

alter table "public"."routes" add constraint "climbs_pkey" PRIMARY KEY using index "climbs_pkey";

alter table "public"."user_favorite_gyms" add constraint "user_favorite_gyms_pkey" PRIMARY KEY using index "user_favorite_gyms_pkey";

alter table "public"."user_profiles" add constraint "user_profiles_pkey" PRIMARY KEY using index "user_profiles_pkey";

alter table "public"."videos" add constraint "videos_pkey" PRIMARY KEY using index "videos_pkey";

alter table "public"."walls" add constraint "walls_pkey" PRIMARY KEY using index "walls_pkey";

alter table "public"."gym_admins" add constraint "gym_admins_gym_id_fkey" FOREIGN KEY (gym_id) REFERENCES public.gyms(id) ON DELETE CASCADE not valid;

alter table "public"."gym_admins" validate constraint "gym_admins_gym_id_fkey";

alter table "public"."gym_admins" add constraint "gym_admins_gym_id_user_id_key" UNIQUE using index "gym_admins_gym_id_user_id_key";

alter table "public"."gym_admins" add constraint "gym_admins_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE not valid;

alter table "public"."gym_admins" validate constraint "gym_admins_user_id_fkey";

alter table "public"."routes" add constraint "climbs_gym_id_fkey" FOREIGN KEY (gym_id) REFERENCES public.gyms(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."routes" validate constraint "climbs_gym_id_fkey";

alter table "public"."routes" add constraint "climbs_wall_id_fkey" FOREIGN KEY (wall_id) REFERENCES public.walls(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."routes" validate constraint "climbs_wall_id_fkey";

alter table "public"."user_favorite_gyms" add constraint "user_favorite_gyms_gym_id_fkey" FOREIGN KEY (gym_id) REFERENCES public.gyms(id) ON DELETE CASCADE not valid;

alter table "public"."user_favorite_gyms" validate constraint "user_favorite_gyms_gym_id_fkey";

alter table "public"."user_favorite_gyms" add constraint "user_favorite_gyms_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_favorite_gyms" validate constraint "user_favorite_gyms_user_id_fkey";

alter table "public"."user_favorite_gyms" add constraint "user_favorite_gyms_user_id_gym_id_key" UNIQUE using index "user_favorite_gyms_user_id_gym_id_key";

alter table "public"."user_profiles" add constraint "user_profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_id_fkey";

alter table "public"."videos" add constraint "videos_route_id_fkey" FOREIGN KEY (route_id) REFERENCES public.routes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."videos" validate constraint "videos_route_id_fkey";

alter table "public"."videos" add constraint "videos_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."videos" validate constraint "videos_user_id_fkey";

alter table "public"."walls" add constraint "walls_gym_id_fkey" FOREIGN KEY (gym_id) REFERENCES public.gyms(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."walls" validate constraint "walls_gym_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  claims jsonb;
  has_username boolean;
BEGIN
  SELECT (username IS NOT NULL AND username != '')
  INTO has_username
  FROM public.user_profiles
  WHERE id = (event->>'user_id')::uuid;

  claims := event->'claims';
  claims := jsonb_set(claims, '{has_username}', to_jsonb(COALESCE(has_username, false)));

  RETURN jsonb_set(event, '{claims}', claims);
END;
$function$
;

create or replace view "public"."gym_admins_with_details" as  SELECT ga.user_id,
    ga.gym_id,
    ga.created_at,
    up.username,
    up.full_name,
    up.avatar_url,
    g.name AS gym_name,
    g.slug AS gym_slug
   FROM ((public.gym_admins ga
     JOIN public.user_profiles up ON ((up.id = ga.user_id)))
     JOIN public.gyms g ON ((g.id = ga.gym_id)));


create or replace view "public"."gyms_with_counts" as  SELECT g.id,
    g.name,
    g.slug,
    g.city,
    g.province,
    g.logo_url,
    g.tags,
    count(DISTINCT r.id) AS route_count,
    count(DISTINCT v.id) AS video_count
   FROM ((public.gyms g
     LEFT JOIN public.routes r ON ((r.gym_id = g.id)))
     LEFT JOIN public.videos v ON ((v.route_id = r.id)))
  GROUP BY g.id, g.slug;


CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
INSERT INTO public.user_profiles (id, email, full_name, avatar_url)
VALUES (
NEW.id,
NEW.email,
NEW.raw_user_meta_data->>'full_name',
NEW.raw_user_meta_data->>'avatar_url'
);
RETURN NEW;
END;

$function$
;

CREATE OR REPLACE FUNCTION public.increment_video_views(video_id integer)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  update videos set views = views + 1 where id = video_id;
$function$
;

create or replace view "public"."profiles_with_counts" as  SELECT up.id,
    up.username,
    up.avatar_url,
    up.created_at,
    up.height,
    g.name AS home_gym,
    count(v.id) AS upload_count,
    COALESCE(sum(v.views), (0)::bigint) AS total_views
   FROM ((public.user_profiles up
     LEFT JOIN public.videos v ON (((v.user_id = up.id) AND (v.upload_status = 'ready'::text))))
     LEFT JOIN public.gyms g ON ((g.name = up.home_gym)))
  GROUP BY up.id, up.username, up.avatar_url, g.name;


create or replace view "public"."routes_with_details" as  SELECT r.id,
    r.created_at,
    r.name,
    r.grade,
    r.color,
    r.gym_id,
    r.wall_id,
    w.name AS wall_name,
    g.name AS gym_name,
    count(v.id) AS video_count
   FROM (((public.routes r
     LEFT JOIN public.walls w ON ((w.id = r.wall_id)))
     LEFT JOIN public.gyms g ON ((g.id = r.gym_id)))
     LEFT JOIN public.videos v ON ((v.route_id = r.id)))
  GROUP BY r.id, w.name, g.name;


create or replace view "public"."videos_with_details" as  SELECT v.id,
    v.user_id,
    v.route_id,
    v.storage_path,
    v.uploaded_by,
    v.created_at,
    v.thumbnail_url,
    v.views,
    v.mux_playback_id,
    v.mux_asset_id,
    v.upload_status,
    v.duration_seconds,
    v.aspect_ratio,
    r.name AS route_name,
    r.grade AS route_grade,
    w.name AS wall_name,
    g.name AS gym_name,
    p.height AS uploaded_by_height
   FROM ((((public.videos v
     JOIN public.routes r ON ((r.id = v.route_id)))
     JOIN public.walls w ON ((w.id = r.wall_id)))
     JOIN public.gyms g ON ((g.id = w.gym_id)))
     JOIN public.user_profiles p ON ((p.username = v.uploaded_by)));


grant delete on table "public"."contact_submissions" to "anon";

grant insert on table "public"."contact_submissions" to "anon";

grant references on table "public"."contact_submissions" to "anon";

grant select on table "public"."contact_submissions" to "anon";

grant trigger on table "public"."contact_submissions" to "anon";

grant truncate on table "public"."contact_submissions" to "anon";

grant update on table "public"."contact_submissions" to "anon";

grant delete on table "public"."contact_submissions" to "authenticated";

grant insert on table "public"."contact_submissions" to "authenticated";

grant references on table "public"."contact_submissions" to "authenticated";

grant select on table "public"."contact_submissions" to "authenticated";

grant trigger on table "public"."contact_submissions" to "authenticated";

grant truncate on table "public"."contact_submissions" to "authenticated";

grant update on table "public"."contact_submissions" to "authenticated";

grant delete on table "public"."contact_submissions" to "service_role";

grant insert on table "public"."contact_submissions" to "service_role";

grant references on table "public"."contact_submissions" to "service_role";

grant select on table "public"."contact_submissions" to "service_role";

grant trigger on table "public"."contact_submissions" to "service_role";

grant truncate on table "public"."contact_submissions" to "service_role";

grant update on table "public"."contact_submissions" to "service_role";

grant delete on table "public"."gym_admins" to "anon";

grant insert on table "public"."gym_admins" to "anon";

grant references on table "public"."gym_admins" to "anon";

grant select on table "public"."gym_admins" to "anon";

grant trigger on table "public"."gym_admins" to "anon";

grant truncate on table "public"."gym_admins" to "anon";

grant update on table "public"."gym_admins" to "anon";

grant delete on table "public"."gym_admins" to "authenticated";

grant insert on table "public"."gym_admins" to "authenticated";

grant references on table "public"."gym_admins" to "authenticated";

grant select on table "public"."gym_admins" to "authenticated";

grant trigger on table "public"."gym_admins" to "authenticated";

grant truncate on table "public"."gym_admins" to "authenticated";

grant update on table "public"."gym_admins" to "authenticated";

grant delete on table "public"."gym_admins" to "service_role";

grant insert on table "public"."gym_admins" to "service_role";

grant references on table "public"."gym_admins" to "service_role";

grant select on table "public"."gym_admins" to "service_role";

grant trigger on table "public"."gym_admins" to "service_role";

grant truncate on table "public"."gym_admins" to "service_role";

grant update on table "public"."gym_admins" to "service_role";

grant delete on table "public"."gyms" to "anon";

grant insert on table "public"."gyms" to "anon";

grant references on table "public"."gyms" to "anon";

grant select on table "public"."gyms" to "anon";

grant trigger on table "public"."gyms" to "anon";

grant truncate on table "public"."gyms" to "anon";

grant update on table "public"."gyms" to "anon";

grant delete on table "public"."gyms" to "authenticated";

grant insert on table "public"."gyms" to "authenticated";

grant references on table "public"."gyms" to "authenticated";

grant select on table "public"."gyms" to "authenticated";

grant trigger on table "public"."gyms" to "authenticated";

grant truncate on table "public"."gyms" to "authenticated";

grant update on table "public"."gyms" to "authenticated";

grant delete on table "public"."gyms" to "service_role";

grant insert on table "public"."gyms" to "service_role";

grant references on table "public"."gyms" to "service_role";

grant select on table "public"."gyms" to "service_role";

grant trigger on table "public"."gyms" to "service_role";

grant truncate on table "public"."gyms" to "service_role";

grant update on table "public"."gyms" to "service_role";

grant delete on table "public"."routes" to "anon";

grant insert on table "public"."routes" to "anon";

grant references on table "public"."routes" to "anon";

grant select on table "public"."routes" to "anon";

grant trigger on table "public"."routes" to "anon";

grant truncate on table "public"."routes" to "anon";

grant update on table "public"."routes" to "anon";

grant delete on table "public"."routes" to "authenticated";

grant insert on table "public"."routes" to "authenticated";

grant references on table "public"."routes" to "authenticated";

grant select on table "public"."routes" to "authenticated";

grant trigger on table "public"."routes" to "authenticated";

grant truncate on table "public"."routes" to "authenticated";

grant update on table "public"."routes" to "authenticated";

grant delete on table "public"."routes" to "service_role";

grant insert on table "public"."routes" to "service_role";

grant references on table "public"."routes" to "service_role";

grant select on table "public"."routes" to "service_role";

grant trigger on table "public"."routes" to "service_role";

grant truncate on table "public"."routes" to "service_role";

grant update on table "public"."routes" to "service_role";

grant delete on table "public"."user_favorite_gyms" to "anon";

grant insert on table "public"."user_favorite_gyms" to "anon";

grant references on table "public"."user_favorite_gyms" to "anon";

grant select on table "public"."user_favorite_gyms" to "anon";

grant trigger on table "public"."user_favorite_gyms" to "anon";

grant truncate on table "public"."user_favorite_gyms" to "anon";

grant update on table "public"."user_favorite_gyms" to "anon";

grant delete on table "public"."user_favorite_gyms" to "authenticated";

grant insert on table "public"."user_favorite_gyms" to "authenticated";

grant references on table "public"."user_favorite_gyms" to "authenticated";

grant select on table "public"."user_favorite_gyms" to "authenticated";

grant trigger on table "public"."user_favorite_gyms" to "authenticated";

grant truncate on table "public"."user_favorite_gyms" to "authenticated";

grant update on table "public"."user_favorite_gyms" to "authenticated";

grant delete on table "public"."user_favorite_gyms" to "service_role";

grant insert on table "public"."user_favorite_gyms" to "service_role";

grant references on table "public"."user_favorite_gyms" to "service_role";

grant select on table "public"."user_favorite_gyms" to "service_role";

grant trigger on table "public"."user_favorite_gyms" to "service_role";

grant truncate on table "public"."user_favorite_gyms" to "service_role";

grant update on table "public"."user_favorite_gyms" to "service_role";

grant delete on table "public"."user_profiles" to "anon";

grant insert on table "public"."user_profiles" to "anon";

grant references on table "public"."user_profiles" to "anon";

grant select on table "public"."user_profiles" to "anon";

grant trigger on table "public"."user_profiles" to "anon";

grant truncate on table "public"."user_profiles" to "anon";

grant update on table "public"."user_profiles" to "anon";

grant delete on table "public"."user_profiles" to "authenticated";

grant insert on table "public"."user_profiles" to "authenticated";

grant references on table "public"."user_profiles" to "authenticated";

grant select on table "public"."user_profiles" to "authenticated";

grant trigger on table "public"."user_profiles" to "authenticated";

grant truncate on table "public"."user_profiles" to "authenticated";

grant update on table "public"."user_profiles" to "authenticated";

grant delete on table "public"."user_profiles" to "service_role";

grant insert on table "public"."user_profiles" to "service_role";

grant references on table "public"."user_profiles" to "service_role";

grant select on table "public"."user_profiles" to "service_role";

grant trigger on table "public"."user_profiles" to "service_role";

grant truncate on table "public"."user_profiles" to "service_role";

grant update on table "public"."user_profiles" to "service_role";

grant delete on table "public"."videos" to "anon";

grant insert on table "public"."videos" to "anon";

grant references on table "public"."videos" to "anon";

grant select on table "public"."videos" to "anon";

grant trigger on table "public"."videos" to "anon";

grant truncate on table "public"."videos" to "anon";

grant update on table "public"."videos" to "anon";

grant delete on table "public"."videos" to "authenticated";

grant insert on table "public"."videos" to "authenticated";

grant references on table "public"."videos" to "authenticated";

grant select on table "public"."videos" to "authenticated";

grant trigger on table "public"."videos" to "authenticated";

grant truncate on table "public"."videos" to "authenticated";

grant update on table "public"."videos" to "authenticated";

grant delete on table "public"."videos" to "service_role";

grant insert on table "public"."videos" to "service_role";

grant references on table "public"."videos" to "service_role";

grant select on table "public"."videos" to "service_role";

grant trigger on table "public"."videos" to "service_role";

grant truncate on table "public"."videos" to "service_role";

grant update on table "public"."videos" to "service_role";

grant delete on table "public"."walls" to "anon";

grant insert on table "public"."walls" to "anon";

grant references on table "public"."walls" to "anon";

grant select on table "public"."walls" to "anon";

grant trigger on table "public"."walls" to "anon";

grant truncate on table "public"."walls" to "anon";

grant update on table "public"."walls" to "anon";

grant delete on table "public"."walls" to "authenticated";

grant insert on table "public"."walls" to "authenticated";

grant references on table "public"."walls" to "authenticated";

grant select on table "public"."walls" to "authenticated";

grant trigger on table "public"."walls" to "authenticated";

grant truncate on table "public"."walls" to "authenticated";

grant update on table "public"."walls" to "authenticated";

grant delete on table "public"."walls" to "service_role";

grant insert on table "public"."walls" to "service_role";

grant references on table "public"."walls" to "service_role";

grant select on table "public"."walls" to "service_role";

grant trigger on table "public"."walls" to "service_role";

grant truncate on table "public"."walls" to "service_role";

grant update on table "public"."walls" to "service_role";


  create policy "Allow anonymous inserts"
  on "public"."contact_submissions"
  as permissive
  for insert
  to anon
with check (true);



  create policy "superusers can manage contact_submissions"
  on "public"."contact_submissions"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.user_profiles
  WHERE ((user_profiles.id = auth.uid()) AND (user_profiles.is_superuser = true)))))
with check ((EXISTS ( SELECT 1
   FROM public.user_profiles
  WHERE ((user_profiles.id = auth.uid()) AND (user_profiles.is_superuser = true)))));



  create policy "Admin can read own rows"
  on "public"."gym_admins"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "superusers can manage gym_admins"
  on "public"."gym_admins"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.user_profiles
  WHERE ((user_profiles.id = auth.uid()) AND (user_profiles.is_superuser = true)))))
with check ((EXISTS ( SELECT 1
   FROM public.user_profiles
  WHERE ((user_profiles.id = auth.uid()) AND (user_profiles.is_superuser = true)))));



  create policy "Enable all access for all users"
  on "public"."gyms"
  as permissive
  for all
  to public
using (true);



  create policy "Enable all access for all users"
  on "public"."routes"
  as permissive
  for all
  to public
using (true);



  create policy "Users can manage their own favorites"
  on "public"."user_favorite_gyms"
  as permissive
  for all
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Enable read access for all users"
  on "public"."user_profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Users can update own profile"
  on "public"."user_profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id));



  create policy "only superusers can set is_superuser"
  on "public"."user_profiles"
  as permissive
  for update
  to public
using ((auth.uid() IN ( SELECT user_profiles_1.id
   FROM public.user_profiles user_profiles_1
  WHERE (user_profiles_1.is_superuser = true))));



  create policy "Enable all access for all users"
  on "public"."videos"
  as permissive
  for all
  to public
using (true);



  create policy "Enable all access for all users"
  on "public"."walls"
  as permissive
  for all
  to public
using (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Avatars are publicly readable"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'avatars'::text));



  create policy "Users can delete their own avatar"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "Users can update their own avatar"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "Users can upload their own avatar"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



